# Generated by Django 6.0.2 on 2026-04-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesnap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pricealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pricealert',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notification_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily')], default='instant', max_length=10),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='target_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_alerts', to='pricesnap.platform'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='pricesnap.platform'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pricesnap.product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pricesnap.user'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='pricesnap.product'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='pricesnap.user'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='pricesnap.platform'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricesnap.product'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='clicked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='pricesnap.product'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='pricesnap.user'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_per_user'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'platform', 'seller_name'), name='unique_product_platform_seller'),
        ),
    ]
